name: dart_ipquery
description: A Dart library to query IP addresses using the ipquery.io API.
version: 1.0.0
repository: https://github.com/avesbox/dart_ipquery
topics:
  - ipquery
  - ip
  - geolocation

environment:
  sdk: '>=3.6.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
